### ISSUE TITLE
Attribution display shifted in 2.7.x and 2.8

### ISSUE THREAD

**Issue by tchaddad** [geomoose/geomoose#100]
Using the Attribution extension, works, except that since 2.7, the location of the attribution is inexplicably shifted up about an inch from the expected lower right corner.

Tripped over this because I'd like to turn attribution on for the OpenStreetMap basemaps (as required by their license). Might also be something to add to the demo?

**Comment by theduckylittle** [comment]
OpenLayers changed the styling, I've updated our CSS to override that "fix."

**Comment by tchaddad** [comment]
Working well - thanks!
