### ISSUE TITLE
Drawing Edit Attributes - Save Clear Selection

### ISSUE THREAD

**Issue by klassenjs** [geomoose/geomoose#101]
I tried the following:

1) Click create a polygon tool
2) Draw a polygon
3) Click the edit attributes tool
4) Click on the polygon
5) Make the changes in the dialog and click save
At this point the polygon is still selected (blue) on the map and the changes don't /appear/ to have taken effect.
6) Click somewhere on the map that is not on the polygon
Now things look as expected.

Thus I confirm and agree, with your assessment: the save action is not clearing the selection and it would be more intuitive if it cleared the selection automatically.

More details: http://lists.osgeo.org/pipermail/geomoose-users/2015-August/005758.html

**Comment by tchaddad** [comment]
Confirm this now works as expected (polygon deselects when attributes are saved).
