### ISSUE TITLE
OpenLayers scale bar missing.

### ISSUE THREAD

**Issue by klassenjs** [geomoose/geomoose#102]
Restore optional OpenLayers generated scalebar from scaleLine.js in version 2.4.

More info: http://lists.osgeo.org/pipermail/geomoose-users/2015-July/005756.html

**Comment by theduckylittle** [comment]
I've restored this functionality (and put the code in "configureMapTools") instead of before its mention in the code.  I changed config.js to set it off by default so it will need to be turned on in the mapbook using a `<param>` tag.

**Comment by elil** [comment]
We should update the docs too, http://docs.geomoose.org/master/docs/configuration.html?highlight=scale_line (at least "Defaults to true" and "lien").  Are the other parts correct?

This doc seems to have multiple sources, see also http://docs.geomoose.org/master/developer/config.html?highlight=scale_line

**Comment by tchaddad** [comment]
Works for me with:

	<param name="scale_line.enabled">true</param>

FYI, I noticed that the default units change depending on the zoom level - close in, it is meters above and feet below, while zoomed way out it is feet above and miles below.

**Comment by klassenjs** [comment]
It mixes meters and feet?  That seems like it should be fixed.
