### ISSUE TITLE
Highlighting missing from select feature tool - MS4W specific

### ISSUE THREAD

**Issue by markvolzlyoncounty** [geomoose/geomoose#107]
Hello,

After using select features, I noticed that the buffer and feature results highlights are missing from the map.  This may be MS4W specific as the demo works fine.

p.s.  ms4w is selecting the correct parcels on the results tab.

**Comment by tchaddad** [comment]
Hi Mark, I think this is the ticket for the issue that Jeff just commented on on the mailing list:
https://lists.osgeo.org/pipermail/geomoose-users/2015-December/005813.html
Can you try his solution and report back and close this issue if his solution works for you?

**Comment by markvolzlyoncounty** [comment]
With a couple changes to the query I can now see highlights as expected in the selection results!

Changes in c:\ms4w\apps\geomoose2\php\highlight.php

Line 47
Replace: DATA 'features' 
With: DATA 'select wkt_geometry from features'

Line 66
Replace: DATA 'selection'
With: DATA 'select area, wkt_geometry from selection'

Thanks Jeff and Tanya!

**Comment by tchaddad** [comment]
So for the record, Jeff's fix is supposed to be applied to this file:

https://github.com/geomoose/geomoose-services/blob/master/php/select/highlight.map

**Comment by tchaddad** [comment]
The ticket should probably remain open until the next review of closeable tickets (in case the fix impacts any other items).

**Comment by theduckylittle** [comment]
Especially since no one actually updated the code, it's relatively important that we left it open.

Code changes here: https://github.com/geomoose/geomoose-services/commit/f63c0e972c2495ac8f12d2a897ee140f098ad7c9
