### ISSUE TITLE
Edit graphics and functionality GeoMoose Windows

### ISSUE THREAD

**Issue by lord112** [geomoose/geomoose#109]
Hello , we have a problem in customizing the interface of geomoose MS4W version 2.8 , how do we proceed ? We can not change the position of TABS , we would also like to add the div below the map , but we can not do that either . Pending thank you

PLEASE HELP ME :(

**Comment by elil** [comment]
Github issues are for tracking things that need to get fixed, not assistance requests. To request assistance, use the mailing list under the [support options] (http://geomoose.org/index.html#geomoose-support).  Some documentation pertaining to the appearance of the application is available  [in the docs] (http://docs.geomoose.org/2.8/howto/skin.html).
