### ISSUE TITLE
Application.getStatusDifferences broken

### ISSUE THREAD

**Issue by klassenjs** [geomoose/geomoose#112]
If `status="on"` is used in the `catalog->layer` instead of the `mapsource->layer` in the mapbook, then the layer still defaults to on in the interface, but `initial_on` never gets set in `Application.mapSources.layer[...]` so that `Application.getStatusDifferences()` never returns any items in the `off` list.

This impacts `GeoMOOSE.getBookmarkUrl()` and new work on the HashTrack extension.

**Comment by theduckylittle** [comment]
This was re-reviewed, and there's now another fix to make this a bit cleaner, it doesn't use "initial_on" anymore but each GeoMOOSE.Layer instance tracks the original state of each path.
