### ISSUE TITLE
Vector editing with WFS-T

### ISSUE THREAD

**Issue by tchaddad** [geomoose/geomoose#117]
Capturing Brent Fraser's fixes for WFS-T editing here so it doesn't get lost:
https://lists.osgeo.org/pipermail/geomoose-users/2016-March/005945.html

- Add controls to the Census Cities layer in mapbook.xml:

```
<layer title="Census Cities"  activate="true" src="census_cities" fade="false" unfade="false" metadata="false" legend="false" draw-point="false" draw-line="false" draw-polygon="true" edit-attributes="true" edit-shape="true" remove-feature="true" remove-all-features="true" buffer="true"></layer>
```

- Add  "auto:true" to the save strategy in GeoMoose's WFS.js (line 36):
```
this.save_strategy = new OpenLayers.Strategy.Save({auto:true});
```
this means that when you unselect the feature after editing the changes will be automatically saved

- Also in WFS.js, change line 44 to be:
```
projection:this.srsName, // new 
OpenLayers.Projection(CONFIGURATION.projection),
```

- In the mapbook add srs="EPSG:4269" to the mapsource:
```
<map-source name="census_cities" type="wfs" active="true" srs="EPSG:4269">
```
this causes OpenLayers to re-project the feature's geometry before passing it to TinyOWS (I don't think TinyOWS does re-projection).

- In the TinyOWS config.xml file, set:
```
check_schema="0"
```
in the TinyOWS config.xml file.  There are some schema problems I need to track down, but this works for now.

- When you create the table in PostGIS using ogr2ogr, make sure it creates it with geometry type of POLYGON by including "*-nlt POLYGON*", otherwise the type is MULTIPOLYGON and PostGIS complains when TinyOWS tries to insert a POLYGON.

**Comment by jmckenna** [comment]
Regarding schema problems, I faced that too with the MS4W demo; to solve that I had to copy the 'schema' folder from the tinyows source into /ms4w/apps/tinyows/, so I bet that you would also have to copy that same folder from /ms4w/apps/tinyows/schema/ to inside your GeoMOOSE application directory, or, as you said, set check_schema to 0.

**Comment by brentfraser** [comment]
Fix successfully tested
