### ISSUE TITLE
Add the ability to get WFS attribute option list via a script

### ISSUE THREAD

**Issue by brentfraser** [geomoose/geomoose#118]
Geomoose v2.6 had an "ajax_select" to get a list for feature editing service combo box via a URL: 
`  <input type="ajax_select" name="feature:featuretype_id"  title=" Type: " value="1">
        <url>php/getFeatureTypes.php</url>
  </input>`
 
And I see that Jim has added combo box ability to the new Geomoose v2.8 WFS mapsource definition: so we can do things like:
`  <attribute name="featuretype_id"  type="select" label=" Type: " default-value="1">
            <option value="1">Iceberg</option>
            <option value="2">Tabular Iceberg</option>`

But it would be nice to get the list via an ajax script.  Something like:
`  <attribute name="featuretype_id"  type="ajax_select" label=" Type: " default-value="1">
            <url>php/getFeatureTypes.php</url>
  </attribute>`

**Comment by theduckylittle** [comment]
Added support.

**Comment by brentfraser** [comment]
Failed testing.  For testing, I added the following to the mapbook for mapsource census_cities:

		<attribute name="lsad10"     type="ajax_select" label=" Type: ">
			<url>php/getFeatureTypes.php</url>
		</attribute>

and created php/getFeatureTypes.php:

  <?php
  header('Content-type: application/xml');
  print '<options>';
  print '<option value="25">City</option>';
  print '<option value="57">Place</option>';
  print '</options>';
  ?>

While the list renders properly in the attribute dialog, GeoMOOSE sends TinyOWS  invalid(-ish)  XML (note the blank <wfs:name> at the bottom):

<wfs:Property><wfs:Name>lsad10</wfs:Name><wfs:Value>25</wfs:Value></wfs:Property>
:
<wfs:Property><wfs:Name>intptlon10</wfs:Name><wfs:Value>-093.0321235</wfs:Value></wfs:Property>
<wfs:Property><wfs:Name></wfs:Name><wfs:Value>25</wfs:Value

Even if the blank name was filled in, it would conflict with the other value in the list with the identical name, so that needs to be fixed too.

**Comment by theduckylittle** [comment]
I found the booger.  The ajax_select was setting "this.options =... this options list" instead of "this.options['options'] = this options list".  That was causing the name of the attribute to be unavailable and did all sorts of ugly things.   

The situation should now be mended.

**Comment by brentfraser** [comment]
Tested, fixed!
