### ISSUE TITLE
Add better "Draw Mode" Icon

### ISSUE THREAD

**Issue by tchaddad** [geomoose/geomoose#125]
From Issue https://github.com/geomoose/geomoose/issues/116 we noticed one problem is confusion for the user about when they are in draw mode. One reason for the confusion is that there is no clear indication from the cursor icon that the mode is different.

Suggestion is to use a specific icon solely for draw mode, so the user is always aware that they are in that mode. A pencil icon, or possibly a crosshair icon might be appropriate.

**Comment by elil** [comment]
There are various pencil icons named "draw_*" [here](https://github.com/geomoose/geomoose-js/tree/master/images/silk)

**Comment by bblammo** [comment]
https://www.google.com/search?q=hand+pencil+icon&ie=utf-8&oe=utf-8

I like a hand/pencil version if one could be found.

**Comment by tchaddad** [comment]
All the current icons are a tiny subset of the hug 'Silk' collection here:
http://www.famfamfam.com/lab/icons/silk/previews/index_abc.png

It could be that somewhere in there there are a few that might work and still fit in with the current scheme. Note that they have one called 'map_edit', and a few others with the 'map_' prefix...

**Comment by tchaddad** [comment]
Actually the link above is the source of the menu icons, I'm not sure where the cursor icons came from...

**Comment by elil** [comment]
For potential icon sources we can look at the noun project too,
https://thenounproject.com/search/?q=edit

**Comment by roemhildtg** [comment]
Just stumbled on this conversation but I thought I would throw in my experience, for icons I've had great luck with the css font library font awesome.

**Comment by tchaddad** [comment]
Yeah Font Awesome is my first choice for icons for GM3. It's unclear if this enhancement will get applied in 2.9, but if it does, we'll probably have to find something that matches the 2.x series at least until GM3 becomes a reality.

**Comment by theduckylittle** [comment]
Unfortunately, a lot of those things go out the door when we talk about cursors.  Cursors are a different set of animals.  GIFs, PNGs, CURs files are required depending on the browser and there's specific configuration to do.  That said, I've made some major changes that now relieves a lot of the code from dealing DIRECTLY with cursors.  

With layer controls, services, and built-in tools there is now code that changes the .olMap div's class list. For example...

When you click the pan/zoomin/zoomout tools the .olMap class will now have class="olMap tool-pan" or "olMap tool-zoomin" depending on the appropriate tool name.  When the user selects a service it will have "class="olMap service-identify" for example.  This can be used to do all sorts of fun CSS tricks with the map.  

This is now also being used to define the cursor that the map is showing.  And it allows for control stacking in an intelligent way.

**Comment by tchaddad** [comment]
Tested. Looks great.
