### ISSUE TITLE
Application.getStatusDifferences broken (differently this time)

### ISSUE THREAD

**Issue by klassenjs** [geomoose/geomoose#127]
Application.getStatusDifferences() is behaving strangely.

In the demo, it appears to always return empty sets for both on and off.

In a local version it is placing the map-source twice (e.g 'L117/L117/all' instead of 'L117/all'). 

(Last time for reference #112)

**Comment by klassenjs** [comment]
There is also a console.log statement in the function that should probably be commented out before the release.

**Comment by theduckylittle** [comment]
I had the demo returning the erroneous lists mentioned, not the empty lists.  I fixed that bug.

**Comment by klassenjs** [comment]
Looks good to me.
