### ISSUE TITLE
Layer status not settable in catalog anymore

### ISSUE THREAD

**Issue by klassenjs** [geomoose/geomoose#128]
Initial layer status was settable in the catalog in 2.8.1, but that is no longer being honored in master 

e.g.:
```
<catalog>
  <layer popups="true" src="L117/all" status="on"/>
</catalog>
```

The code in 2.8.1 is here:
https://github.com/geomoose/geomoose-js/blob/r2.8.1/geomoose/GeoMOOSE/Layer.js#L157

**Comment by klassenjs** [comment]
It looks like <catalog><layer show-legend="false"> is being ignored too.

**Comment by theduckylittle** [comment]
The code got refactored a bit for 2.9 and some settings got centralized.  I've appropriately patched the code to restore the ability in the catalog.

**Comment by klassenjs** [comment]
It is now working for me.
