### ISSUE TITLE
Popups clear erratically

### ISSUE THREAD

**Issue by klassenjs** [geomoose/geomoose#129]
With popups.clearOnMove=true: (Also see #122)

In 2.8.1 - popups would disappear immediately on mouse move

In 2.9pre - move right (over the popup) and popup clears immediately, move left (away from popup) and the popup sticks (multiple popups can accumulate with no clicks).  However, all unclicked popups clear simultaneously when the mouse leave the map div (into the catalog/header/etc).

**Comment by theduckylittle** [comment]
I think I've made this more better.

**Comment by klassenjs** [comment]
Also verified fixed.
