### ISSUE TITLE
Select highlight inconsistently incomplete

### ISSUE THREAD

**Issue by elil** [geomoose/geomoose#131]
Sometimes (does not appear to be consistently replicable) the highlighted selection set is incomplete.  This is similar to #84.  Side bar and labels appear correct, it is only the highlight that is partial.  
![select_highlight_partial](https://cloud.githubusercontent.com/assets/5263258/14464674/ac266c54-0084-11e6-9f12-974fa2c5302e.png)

**Comment by theduckylittle** [comment]
Eli, any chance this was related to #134 ? I'm not seeing anything of the like locally.

**Comment by theduckylittle** [comment]
Addendum: If we cannot recreate, I might just tag this as "future" and drop the review label.

**Comment by tchaddad** [comment]
I tried recreating, and the only place I saw something similar looked like it was a road right of way (so probably nothing to select.

![selection_example](https://cloud.githubusercontent.com/assets/1042618/14510876/ac090fce-0188-11e6-8132-276c01ddf3fd.png)

**Comment by klassenjs** [comment]
Looking at the area west of the '4200 parcel with the air photo confirms
the unselected area is a street.

**Comment by klassenjs** [comment]
There is a polygon there.  But PARC_CODE is 11 not 1 and so is being
filtered out in the mapfile.

**Comment by tchaddad** [comment]
I'm pretty sure this one is solved. The non-data areas do not count as errors. @elil 's original area works after the fix too:

![selection_exampleii](https://cloud.githubusercontent.com/assets/1042618/14538086/cd4e547c-022e-11e6-9cbf-e1717804cd0f.png)

**Comment by elil** [comment]
Closing after not encountering with a dozen or so attempts.
