### ISSUE TITLE
Identify PIN report does not appear

### ISSUE THREAD

**Issue by elil** [geomoose/geomoose#132]
The PIN report from the identify tool does not appear to pop up.  I've configured my browser (ff ESR 38.7.0 and ff 45.0.1) to allow popups from demo.geomoose.org

**Comment by theduckylittle** [comment]
I believe this was related to the printing error we fixed.  The Parcel report is really a special case of the print service and was using the same libraries.

**Comment by tchaddad** [comment]
Working for me in the demo at this point - @elil can you confirm?

**Comment by elil** [comment]
Yup, works.
