### ISSUE TITLE
Edit attributes is very difficult to select a line

### ISSUE THREAD

**Issue by elil** [geomoose/geomoose#133]
"Change attributes for a feature in drawing and markup" is very difficult with line features.  I can change attributes for points and polygons with ease but can't get it to select a line with fewer than 20 tries.  I can select a line to edit the shape in usually 2 tries.

**Comment by theduckylittle** [comment]
Added support for box selections when editing attributes.

Adding this same type of select to editing the line is a pretty complicated set of operations that would need broken out to a different ticket.

**Comment by tchaddad** [comment]
I just tried to test this in the demo from FF 45.0.2, and while I can select points, lines and polygons just fine, there are no actual "edit attributes" options that come up.

**Comment by elil** [comment]
Confirm what @tchaddad reports, can select to edit, but edit box does not
appear.

**Comment by theduckylittle** [comment]
Found the issue, there is a demo of how to do a server-populated select box in the edit attributes dialog and a I never bothered to include that PHP script in the services repo.  That's been addressed.

**Comment by elil** [comment]
What is the "Ajax Select" drop down supposed to effect other than demonstrating a server populated select box?  I edit attributes, choose a color from the Ajax select drop down, hit save and everything appears the same color.  Was something supposed to change color from that drop down selection?  

Selecting with a box is indeed easy and successful.

**Comment by theduckylittle** [comment]
Uh... that's all it does.  I should make it do something more useful but demonstrable functionality is always ... uh ... good?

**Comment by theduckylittle** [comment]
I'm willing to entertain a new ticket deprecating the demonstration of ajax_select  but will close the original ticket as it now shows itself as working on the demo.
