### ISSUE TITLE
"x" out of select features does not properly reset select polygon state

### ISSUE THREAD

**Issue by elil** [geomoose/geomoose#134]
1. Choose Select features tool, draw polygon, hit go
2. Hit "x" to close Select Features tab
3. Choose Select features tool, draw polygon (in a different spot), hit go 
4. Notice that selection is from first select polygon

**Comment by theduckylittle** [comment]
Found a bug with how layer redraws were being called... like the using the wrong OpenLayers function.

**Comment by tchaddad** [comment]
Working for me in the demo - thanks for the clear steps to reproduce.
