### ISSUE TITLE
Check dependant files for ResultsAsGrid

### ISSUE THREAD

**Issue by tchaddad** [geomoose/geomoose#135]
In attempting to test ResultsAsGrid with the demo I ran into a few issues that are not exactly bugs, but may need to be looked into (probably documentation again)... I was following on from the stub of info here: http://docs.geomoose.org/master/extensions/ResultsAsGrid.html

and added what I think are all the dependancies:
- dojo.require('dojo.store.Memory');
- dojo.require('dojo.data.ItemFileWriteStore');
- dojo.require('dojo.data.ObjectStore');
- dojo.require('dojox.grid.DataGrid');
- dojo.require("dojox.grid._CheckBoxSelector")
- dojo.require('dijit.Toolbar');
- dojo.require('dijit.layout.BorderContainer');

But still having no luck - console errors and general GeoMoose unhappiness. Need to catch a bus or would delve further. Putting this here for now so we don't forget...

**Comment by klassenjs** [comment]
I'm a little confused, I didn't have to do anything with dependencies.

I the process I used was:
* copy ./extensions/ResultsAsGrid/DemoResultsAsGrid.js to ./extensions/MyResultsAsGrid.js.
* Modify MyResultsAsGrid.js to match my dataset
* Add the line ```dojo.require('extensions.ResultsAsGrid.MyResultsAsGrid');``` to ./site/includes.js
* Run ./libs/build_js.sh to rebuild GeoMoose (including the MyResultsAsGrid) into ./build/dojo/dojo.js

**Comment by theduckylittle** [comment]
Jim's right but I've added some additional information to the extension page.  This one is going to be a struggle for folks because it requires some programming chops to really use effectively.

**Comment by tchaddad** [comment]
Thanks, I'll take a look over the weekend and attempt with Jim's steps when I'm at a different setup than our work environment provides.

**Comment by tchaddad** [comment]
This slipped through the cracks earlier and I probably won't have time to test this one today - but since it's primarily a docs topic, we can chip away at it after your current release...

**Comment by theduckylittle** [comment]
I've got some testing to do here as well.  Jim's got a bigger "schema" bug with the resultsasgrid that needs to be fixed before release.

**Comment by klassenjs** [comment]
We can't delay the release any more.  We need a release to build next weeks
workshop against and to get on OSGEO Live 10.

My vote is to bump ResultsAsGrid to 2.9.1 or 2.10 or mark it experimental
and hide it in the demo.  It is a huge block of new code and is still very
experimental.

**Comment by theduckylittle** [comment]
I'm closing this issue for now (as I think the dependencies are working but we can test more later) and creating a new issue to address more problems with it later.
