### ISSUE TITLE
Buffer these results (buffered_select_followup) does not start

### ISSUE THREAD

**Issue by elil** [geomoose/geomoose#136]
1. Select some parcels
2. Hit the "Buffer these results" link
3. Nothing appears to happen
4. Expected result is a dialogue box with option to set distance and then a new selection result based on that.

**Comment by tchaddad** [comment]
Confirmed.

**Comment by theduckylittle** [comment]
Found the problem.  It was configured to use the old select.php instead of updated for the new, better, sexier query.php.

**Comment by theduckylittle** [comment]
Tested a few of these on the demo and everything seems to be functioning to spec.

**Comment by elil** [comment]
Somehow I missed testing this.  Thanks for fixing and testing.
