### ISSUE TITLE
WFS-T does not save attibute values

### ISSUE THREAD

**Issue by brentfraser** [geomoose/geomoose#139]
While GeoMoose's WFS-T (>= v2.8.1) implementation (with TinyOWS and PostGIS)  does save geometry edits, it does not save attribute edits.  To show the problem, configure the Census Cities WFS-T layer, edit an attribute (e.g. Name) of a city. click the Save dialog button.  While the edit is shown on the map the data is not save to the database.

**Comment by brentfraser** [comment]
I've been able to get the attributes save by editing AttributeEditor.js around line 151:
`
				if(this.feature.state != OpenLayers.State.INSERT) {
					this.feature.state = OpenLayers.State.UPDATE;
				};
				
				//this.feature.layer.save();  // this should work, bu there is no save function?
				this.feature.layer.strategies[1].save();  //this does work, but needs to be improved.
				this.hide();
`

The WFS layer has a save function defined so it should be available, but isn't.  Strange.

**Comment by theduckylittle** [comment]
I went a little different here.  Now when the save button it calls the MapSource.save() function which normalizes the OpenLayer's operations.

**Comment by brentfraser** [comment]
Well done.
