### ISSUE TITLE
Print Service ArcGis Server WMS Can't parse XML request.

### ISSUE THREAD

**Issue by federicogodan** [geomoose/geomoose#145]
we are using geomoose 2.8.1, but when add a map-source to mapbook with format wms provided by ArcGis Server:
`<map-source name="geoservicios_dinamige" type="wms" tiled="false" queryable="true">
 <url>http://visualizadorgeominero.dinamige.gub.uy:8081/arcgis/services/Catastro_Minero/MapServer/WMSServer?</url>
<layer name="0" title="Cantera Obra Publica"/>	
</map-source>`

the url generate to the request is like:
` http://visualizadorgeominero.dinamige.gub.uy:8081/arcgis/services/Catastro_Minero/MapServer/WMSServer?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&SRS=EPSG:3857&FORMAT=image/png&WIDTH=1462&HEIGHT=924&BBOX=-6555330.8113842,-4021050.4980139,-6259366.6379052,-3833997.9013691&LAYERS=0&TRANSPARENT=TRUE&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&LAYERS=0&_OLSALT=0.97904221065196`

then: `SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap` atrributes were repeated on the request. Our geoserver (2.3.4+) dont have problems dealing with duplicated attributes but the ArcGis Server is returning:

`<ServiceExceptionReport version="1.1.1">
<ServiceException code="InvalidFormat">Can't parse XML request.</ServiceException>
</ServiceExceptionReport>`

**FIX**
on print_util.php method getWMSImage:
changing line
`$url = $url . 'SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&EXCEPTIONS=application%2Fvnd.ogc.se_inimage
`
to:
`$url = $url . 'EXCEPTIONS=application%2Fvnd.ogc.se_inimage';
`
and commenting  (deleting) line:
`$url = $url . '&LAYERS='.implode(',', $layer['layers']);`

**Comment by theduckylittle** [comment]
I've updated the way getWMSImage handles default parameters in a better way.  It checks to see if the value is already set in layer['params'] and if it is not then and only then will add it to the params.

**Comment by federicogodan** [comment]
&LAYER= 
stil is added two times to wms getmap url

the layers are checked andor added in if($layer['params']['LAYERS']) but hey are added again in the foreach loop.

**Comment by theduckylittle** [comment]
Odd, because I've set a  check for that on line print_util.php:159 that should stop that from happening.  But even with that statement you're seeing a duplicate layers list?

**Comment by federicogodan** [comment]
i found it!!! the name of the failed layer is "0", then if($layer['params']['LAYERS']) is taken as false so LAYER=0 is added... after that is added once more time in the foreach loop.

maybe we can check layers name length instead of name

**Comment by theduckylittle** [comment]
Okay, it now checks for that '0' situation more explicitly.  PHP has some odd quirks and I miss a few of them from time-to-time.

**Comment by theduckylittle** [comment]
As I don't have a resource we can use to test this aaaand @federicogodan was being pretty responsive... maybe this is fixed? Closing and seeing if a new issue will popup.

**Comment by tchaddad** [comment]
We can test this using the following service:

https://coast.noaa.gov/arcgis/services/MarineCadastre/PhysicalOceanographicAndMarineHabitat/MapServer/WMSServer?request=GetCapabilities&service=WMS

Will attempt soon...

**Comment by theduckylittle** [comment]
Re-opened.  Thanks TC.  Here I am recklessly closing out tickets.  I warned people what happens when the devs do the 'testing'.

**Comment by tchaddad** [comment]
I tested this today, with the "Weather Radar Impact Zones" service listed at the URL above and can confirm that printing will work from a ArcServer layer named '0'. Prints fine at all three levels of quality.

Tested with GM nightly g4c18fb6
