### ISSUE TITLE
ResultsAsGrid Extension Fails with Multiple Data Sources

### ISSUE THREAD

**Issue by theduckylittle** [geomoose/geomoose#147]
When select only works with one dataset ResultsAsGrid works as expected, with more than one, odd errors occur that cause the grid to be unresponsive to data changes.

**Comment by theduckylittle** [comment]
@klassenjs Here be your fixes.  Took me a month of on-and-off time to get this finally fixed.

**Comment by theduckylittle** [comment]
@klassenjs , Any chance to test this yet?

**Comment by klassenjs** [comment]
Not yet.

**Comment by klassenjs** [comment]
Looks good.
