### ISSUE TITLE
Printing at Highest quality results in black background with raster layer

### ISSUE THREAD

**Issue by brentfraser** [geomoose/geomoose#148]
On Windows, when printing at Highest Quality (using defaults for other print settings), instead of a white background, a black background is rendered in the Image, HTML, and PDF options.  Using Higher and Standard resolution correctly renders a white background.

To test, turn on the Weather Radar layer in the demo and do Print.

**Comment by tchaddad** [comment]
So I can confirm your result, but can also confirm there is no bug. The error message that is generated is:

`WMS server error. Image size out of range, WIDTH and HEIGHT must be between 1 and 2048 pixels.`

This is simply a server build issue - if the server were compiled to generate images that go to say, 4000 pixels, this error would not occur.

**Comment by klassenjs** [comment]
Future item might be to automatically tile the layer for the printout when
this happens.

(If the WMS server is MapServer there is a MAXSIZE parameter in the mapfile
that can be adjusted.)

**Comment by brentfraser** [comment]
Sounds like a good approach.
