### ISSUE TITLE
Previous Extent - Next Extent - Full Extent highlighted after use

### ISSUE THREAD

**Issue by federicogodan** [geomoose/geomoose#149]
If next extent (and the other extent options) are pressed one after the other they stay selected in the toolbar until other tool buttom are pressed. I see that prev extent and next extent only work one time after user interaction (cant play pressing prev/next infinite times :-P )

Maybe we can enhance this tools for "remember" more than one step back/next.

**Comment by klassenjs** [comment]
I think the intent is to move away from those tools and to using the
browser back and forward buttons to handle application state.

**Comment by federicogodan** [comment]
the buttons tool on app are ok, just need to be enhance. Using browser buttons can confuse some users (in some aplications pressing browser back button take the user out of the aplication) also this restricts the ability to embed the application within a site (using iframes for example)

**Comment by tchaddad** [comment]
Out of curiosity how many steps would you like to preserve? Myself, I would maybe say 3 at maximum, but I'm not a user of these buttons, so I have no concept of what would be useful.

**Comment by federicogodan** [comment]
between 3 and 10 is ok, usually users tend not to go too far back

**Comment by theduckylittle** [comment]
This wasn't a problem with the forward/back functionality programmed into GeoMoose but with the way the toolbar buttons were being handled in 2.9.  We updated a lot of control interaction and un-selectable tools were apparently missed in that testing.

I think I've fixed the issue but it merits some testing.

**Comment by elil** [comment]
A quick testing indicates that this works through ten or more zoom extents.  Interspersing select, identify, pan, with zoom history clicks appears to not impact extent history.  If we keep track of the status of extent history, we could turn these icons on and off at the beginning and end of the history.

**Comment by theduckylittle** [comment]
I'm calling it good.
