### ISSUE TITLE
Google Geocoder does not work in demo

### ISSUE THREAD

**Issue by markvolzlyoncounty** [geomoose/geomoose#150]
Hello,

I noticed that the Geocoder does not appear to work in the demo.

**Comment by theduckylittle** [comment]
We actually have a problem with both of the geocoder examples in the services right now:
1. Google has made their terms of service more ... 'hostile' to those without an API key.   The API also becomes randomly unavailable.  I haven't found any particular rhyme nor reason to it.
2. geocoder.us appears to be defunct.   This was the default geocoder, not Google.

I've updated the scripts to function but I believe I've also written an email to the PSC on guidance about including the Google Geocoder by default.  I've made the change for now but it could very likely be backed out later.  

There is now a 'Future' ticket to do something else about geocoding.

**Comment by tchaddad** [comment]
Just attempted to test this, and found that all addresses tested result in: "Unable to resolve address". 

Any ideas?

**Comment by theduckylittle** [comment]
I just wrote a test for the google geocoder and it appears to be passing locally.

**Comment by tchaddad** [comment]
OK - just retested on a clean install of 2.9, and can confirm it's working well. Sorry for the noise.
