### ISSUE TITLE
Search Result Highlight is Missing

### ISSUE THREAD

**Issue by tchaddad** [geomoose/geomoose#156]
Testing on the live demo, if we do a search, then click a result and zoom to it, all is working except when you arrive at the selected parcel, there is no highlight.

Pretty sure it was there before! Someone else should confirm.

**Comment by klassenjs** [comment]
By live demo do you mean demo.geomoose.org or the OSGeo Live DVD?

**Comment by tchaddad** [comment]
Apologies for not clarifying sooner - I meant the live demo at demo.geomoose.org

**Comment by cassiel74** [comment]
I can confirm this, release 2.9.0

**Comment by tchaddad** [comment]
Can we bump this issue for consideration in 2.9.1?

**Comment by theduckylittle** [comment]
Just got done chatting with @klassenjs ...
1. We had a snafu in the release cycle and ended up making a 2.9.1 without releasing it publically.
2. He's working on a 2.9.2 that should be published by COB.
3. I've just created a 2.9.3 milestone assigned it here and assigned myself to it.

I can't get to this today but I will try to get to it by EOW.  3.0 and real work have been where most of my time is at.

**Comment by tchaddad** [comment]
No worries - thanks for taking it on!

This is one of those bugs that isn't all that obvious, but when I give someone a tour of the demo, I always kick myself for not having looked into it since first reporting.

**Comment by theduckylittle** [comment]
That should do it, master appears to be healed: http://demo.geomoose.org/master/

@tchaddad , can you just double-triple-super verify?

**Comment by elil** [comment]
Works by my understanding.

Eli

**Comment by tchaddad** [comment]
Hmm, I'm going to need a little more time to test. I can confirm seeing the select color (yellow), but is there not also a highlight color that is supposed to activate when a specific polygon is zoomed to?

**Comment by theduckylittle** [comment]
I've seen some folks add that but I don't ever remember having that in the demo.

**Comment by tchaddad** [comment]
Ah ok then - confirming that it seems to work as expected now. 

This leads me to another question that could turn into a separate enhancement issue - are there some basic selection result set manipulations that can more easily be exposed? I'm thinking things like
- highlight within selection
- remove from current selection

There are probably others, but these are the ones that immediately come to mind...

**Comment by theduckylittle** [comment]
Feel free to file them as new tickets.  A few of those features are coming to GM3.

**Comment by tchaddad** [comment]
Will do, and closing here.
