### ISSUE TITLE
search service on postgis not working

### ISSUE THREAD

**Issue by cassiel74** [geomoose/geomoose#159]
Hi, I believe this could be a bug.
Search in postgis layer doesn't work, here follows my service configuration but really it's just the demo search_parcel with "layer0" and "fieldname0" changed to match my layer source.

        <service name="search_parcels" title="Search" clear-highlight="true">
                <url>php/query.php</url>
                <step type="input">
            <help-text><![CDATA[
                X cerca X
                        ]]></help-text>
                        <input type="hidden" name="highlight" value="true"/>
                        <input type="hidden" name="mode" value="search"/>

                        <input type="hidden" name="layer0" value="rendistat/lazio"/>
                        <input type="hidden" name="template0" value="itemquery"/>

                        <input type="select" name="fieldname0" title="Cerca per:">
                                <option value="den_amm_tit">Amministrazione titolare</option>
                                <option value="cod_cup">Codice CUP</option>
                        </input>
                        <input type="select" name="comparitor0" title="That: ">
                                <option value="like-icase">Contains</option>
                                <option value="right-like-icase">Begins With</option>
                                <option value="eq-str">Matches Exactly</option>
                                <option value="in">In List</option>
                        </input>
                        <input type="user" name="value0" title=""/>
                </step>
        </service>

Here is the php_errors log when submitting a search:

[25-Oct-2016 13:41:10 Europe/Berlin] Got parameters.
[25-Oct-2016 13:41:10 Europe/Berlin] Parsed.
**[25-Oct-2016 13:41:10 Europe/Berlin] ,,,**
[25-Oct-2016 13:41:10 Europe/Berlin] extent'd.
[25-Oct-2016 13:41:10 Europe/Berlin] Search Layer: rendistat/lazio Template: itemquery FILTER: upper(den_amm_tit) like '%'||upper('maletto')||'%'
[25-Oct-2016 13:41:10 Europe/Berlin] 1
[25-Oct-2016 13:41:10 Europe/Berlin] templates/search_result.html
[25-Oct-2016 13:41:10 Europe/Berlin] queryLayer opened

I've noticed that this last differs from the log obtained searching parcels layer, after 'Got parameters' and 'Parsed' my log shows a line with only commas while running the search on parcels layer outputs this (in bold the relevant lines)
[25-Oct-2016 12:27:02 Europe/Berlin] Got parameters.
[25-Oct-2016 12:27:02 Europe/Berlin] Parsed.
**[25-Oct-2016 12:27:02 Europe/Berlin] 477595.80594479,4923984.423582,497205.40936712,4942511.9463291**
[25-Oct-2016 12:27:02 Europe/Berlin] extent'd.
[25-Oct-2016 12:27:02 Europe/Berlin] Search Layer: parcels/parcels Template: itemquery FILTER: ("[OWNER_NAME]" ~* "frank") 
[25-Oct-2016 12:27:02 Europe/Berlin] 
[25-Oct-2016 12:27:02 Europe/Berlin] templates/search_result.html
[25-Oct-2016 12:27:02 Europe/Berlin] queryLayer opened
[25-Oct-2016 12:27:02 Europe/Berlin] queryLayer queried
[25-Oct-2016 12:27:02 Europe/Berlin] queryLayer iterated through.
[25-Oct-2016 12:27:02 Europe/Berlin] Total Results: 3
[25-Oct-2016 12:27:02 Europe/Berlin] qLayer finished
[25-Oct-2016 12:27:02 Europe/Berlin] N FEATURES: 0

it seems just like something is going wrong with the layer EXTENT

**Comment by theduckylittle** [comment]
Can you include the relevant LAYER definition from your Mapfile?

**Comment by cassiel74** [comment]
Here we are
`
MAP
    NAME 'rendis'
    UNITS meters
    EXTENT 569751.46 4235052.07 2058863.21 5952096.57

    PROJECTION
        'init=epsg:3857'
    END

    WEB
        TEMPLATE 'map.html'
        IMAGEPATH '/home/www/tmp'
        IMAGEURL '/ms_tmp/'

        METADATA
            'ows_title'                 "rendistat"
            'ows_srs'                   'EPSG:3857 EPSG:32632 EPSG:4326'
            'ows_enable_request'        '*'
        END  # Metadata
    END  # Web

    LAYER #
        NAME 'lazio'
        TYPE point

        CONNECTIONTYPE postgis
        CONNECTION "host=xxx.xx.xx.xx dbname='xx' user='xxx' password='xxxx' port='5433'"
        DATA 'geom FROM rendistat.v_rendisgeo using unique gid using srid=3857'

        TOLERANCE 50
        TOLERANCEUNITS meters

        PROJECTION
            'init=epsg:3857'
        END

        METADATA
            "identify_record"               "templates/identify_sostegni.html"
            "identify_header"               "templates/header.html"
            'itemquery'                     'templates/search_result.html'
            'itemquery-filter'              '/.*[qstring].*/i'
            'qstring_validation_pattern'    '.'
            'popups'                        'interventi_popup.html'
        END  # Metadata

        TEMPLATE "interventi_popup.html"
        LABELITEM cod_cup
        CLASS
            NAME "Interventi"
            COLOR  255 74 74
            OUTLINECOLOR 5 5 5
            SIZE 6
            SYMBOL 'circle'
        END  # Class
    END # Layer
END # Map
`

**Comment by theduckylittle** [comment]
In the LAYER add

EXTENT -20026376.39 -20048966.10 20026376.39 20048966.10

Sorry if my syntax is off a little bit, I'm doing this on mobile.   MapServer requires an extent (bounding box) for the data queries in databases.  It's just a quirk of the database drivers.  The above should be the global coordinates for 3857.

**Comment by cassiel74** [comment]
No success, still got the empty exent line:

[25-Oct-2016 14:52:23 Europe/Berlin] Got parameters.
[25-Oct-2016 14:52:23 Europe/Berlin] Parsed.
**[25-Oct-2016 14:52:23 Europe/Berlin] ,,,**
[25-Oct-2016 14:52:23 Europe/Berlin] extent'd.
[25-Oct-2016 14:52:23 Europe/Berlin] Search Layer: rendistat/lazio Template: itemquery FILTER: upper(den_amm_tit) like '%'||upper('MALETTO')||'%'
[25-Oct-2016 14:52:23 Europe/Berlin] 1
[25-Oct-2016 14:52:23 Europe/Berlin] templates/search_result.html
[25-Oct-2016 14:52:23 Europe/Berlin] queryLayer opened

**Comment by cassiel74** [comment]
I must apologize, it works, I did add the EXTENT in the MAP section instead of LAYER one.
Thank you!

IMHO this should be pointed in the doc

**Comment by theduckylittle** [comment]
I just added a warning note here: http://docs.geomoose.org/master/howto/layer.html

If there's a better place that you would like to see please feel free to update this ticket.  For now, I'll close it out.

**Comment by cassiel74** [comment]
I believe it should be referred here http://docs.geomoose.org/2.6/howto/search.html
but I saw there's no 2.9.X equivalent in the docs
