### ISSUE TITLE
The link to the GM3.0 (beta) Demo from home page is broken.

### ISSUE THREAD

**Issue by bblammo** [geomoose/geomoose#164]
This is the current link:  http://demo.geomoose.org/3.0/demo/

and 

this one worked for me: http://demo.geomoose.org/3.0/

**Comment by klassenjs** [comment]
I am not aware that we have an official link for the 3.0 demo yet.  Is the
first linked anywhere that needs to be changed?

**Comment by bblammo** [comment]
Just go to geomoose.or  the 3.0 version is listed and linked to.

**Comment by elil** [comment]
I seem to have forgotten how to correctly reference tickets in [PRs](https://github.com/geomoose/geomoose-website/pull/5)

**Comment by theduckylittle** [comment]
Ish happens. Looks great! Closing.
