### ISSUE TITLE
Restore Dynamic Zoom Extension

### ISSUE THREAD

**Issue by bfischer-hei** [geomoose/geomoose#27]
In prior versions of GeoMoose there was a Dynamic Zoom extension. This was never ported to GM 2.6. This extension needs to be reviewed to see if the functionality can be ported to 2.6. This should also likely be removed from the GeoMoose documentation until the feature is restored.

http://www.geomoose.org/extensions/DynamicZoom.html

**Comment by theduckylittle** [comment]
Updated documentation link: http://docs.geomoose.org/2.4/extensions/DynamicZoom.html

**Comment by theduckylittle** [comment]
Jim and I banged our heads together on this for a while and wanted to see if we could offer a better solution.  The result is a bit of an old city creation called "fido."  It fetches data, see, like a dog, named Fido. Clever developers.

How this works:
1. There is now an extension called "FidoSearch".  It takes a URL which returns JSON.  The JSON is a list formatted thusly:
<pre>
[ 
 ...
 {"label" : "The Label" , "extent" : [minx,miny,maxx,maxy]}
 ...
]
</pre>
  The FidoSearch extension makes a searchable drop-down list.  When the user clicks on the result, it zooms them to that area.  
2. fido.php works with the mapbook to make map-sources search able.  To make a searchable mapfile:
   1. Add fido-search="true" to the <map-source>
   2. In the mapfile ensure the following:
      1. All searchable layers have a PROJECTION element set.
      2. All searchable layers have a "fido_record" template.  basemap.map has an example of i and ii.
      3.  The "fido_record" template will look like this (example is for counties from the demo):
<pre>

{"label" : "[COUNTYNAME] County", "extent" : [[shpext format="$minx,$miny,$maxx,$maxy" proj="epsg:4326"]]}
</pre>

**Comment by elil** [comment]
d4ae637 makes it look like this should be in the demo but I don't see any way to access this in the UI, perhaps via, "Jump To:"  Is it in the demo?  If so, where?
