### ISSUE TITLE
Popup floating, click to stick (vs hover to stick)

### ISSUE THREAD

**Issue by bblammo** [geomoose/geomoose#45]
There are two different workflow processes that have been identified for using popups on a layer.

1.)  The current action on a popup enabled layer is to hover over a feature to have a popup appear and stick on the map.  These disappear upon map navigate.

2. ) Would like to also have the option of being able to click to stick.  The hover action would be to initiate a popup, but mouse movement would close the popup when the underling mouse over feature changes, and a new popup appears.  Clicking the popup would then stick the popup.  These can then disappear on map navigate.

Suggested possible solution, could this be a Layer level control toggle, pre-pinned dialog vs floating dialogs?

**Comment by elil** [comment]
@bblammo, can you review this?

**Comment by bblammo** [comment]
Looks fine to me. Has this been added to the demo already?

**Comment by bblammo** [comment]
You need to set up a configuration for each type in order to test it.

The way we implement it at the City has been to click to stick, and that 
was across the board.  I suspect that it will be used in the same manner 
by most folks, all layers with one setting.  But you could mix the 
actions as I understand how it's been implemented. We've tested the 
alpha code on this at the City extensively.

bobb
