### ISSUE TITLE
Selection and Query Tool enhancements with vector output

### ISSUE THREAD

**Issue by bfischer-hei** [geomoose/geomoose#60]
Contributed code for RFC 5.  http://www.geomoose.org/rfc/rfc-5.html  Only tested on GM 2.6.1 at this point.

https://github.com/geomoose/geomoose/pull/40

**Comment by bfischer-hei** [comment]
HEI has worked on the code to update it to work with master in January.  We have one more review we would like it to go to before pushing the updated code to github.  We will target to get this completed by end of May.

**Comment by elil** [comment]
Great!  Let me know if I can help.

**Comment by theduckylittle** [comment]
Bumping this to future for now.  Will consider for 2.9/3.0.

**Comment by theduckylittle** [comment]
Closing this out as it was a bit of a parent ticket.  Subsequent problems can be reported individually.
