### ISSUE TITLE
Geomoose - save-load and reading offline ?!

### ISSUE THREAD

**Issue by s4mf** [geomoose/geomoose#67]
Hey guys , 
Actually I just wondering is there anyway to save shapes (point , line , polygons and so on.) to a file and then again just load that and it's shows again on the map ?

another question is, is there anyway to reading the offline map and use geomoose in offline mode ?
if yes how?
thanks a lot ...

**Comment by theduckylittle** [comment]
Please try email the mailing list with questions:
- geomoose-users@lists.osgeo.org
