### ISSUE TITLE
Allow Current Extent to Persist After Reload/Refresh

### ISSUE THREAD

**Issue by lfilak** [geomoose/geomoose#68]
By allowing the Current Extent to be accessed as "Previous Extent" following a browser reload an opportunity exists to satisfy the following needs, and perhaps more.
1) Restore layer selections to default without the need to re-identify a map location/extent.
2) Clear misc. browser layers of artifacts produced periodically by poor mouse clicks, IE. shaded zoom box that remains in the display because both mouse buttons were pressed while dragging the box.
3) Possibly allow for accidental picks on the browser back button, so a forward & previous extent will restore the map extent.

**Comment by theduckylittle** [comment]
I wrote an extension that preserves the location history in the hash tag.  Layers on/off is not currently tracked.  If someone *really* wants that maybe we can look at adding another ticket to the repo.

**Comment by lfilak** [comment]
Thank you.
Is there a use example available?

**Comment by theduckylittle** [comment]
Of course not! :)  Documentation is for the organized.

Here is the code (which you can download into a 2.7 install's "extensions/" directory:
- https://github.com/geomoose/geomoose-js/blob/master/extensions/HashTrack.js

Then in your HTML file, before the `</head>` tag add:
`<script type="text/javascript" src="extensions/HashTrack.js"></script>`

That should be it.

**Comment by lfilak** [comment]
Thank you.
I guess that means that you just became organized, if you weren't already.

**Comment by theduckylittle** [comment]
Officially doc'd.
