### ISSUE TITLE
Select Features fails with 500 error on invalid input shape

### ISSUE THREAD

**Issue by klassenjs** [geomoose/geomoose#69]
Tested in 2.7.1
To reproduce:  Activate Select Features, select draw polygon, click once on the map, double click on the map (to end the "polygon") produces a two point polygon, click Go!.

The 500 error is confusing to users and looks broken.  Suggest either it should work as a line select or give a useful error message.

**Comment by theduckylittle** [comment]
PULL REQUEST OR DIE.

Also, Hi Jim.

**Comment by klassenjs** [comment]
Hmm... This might be more on the JS side.  I just broke print (with another 500 error) by making a 2 point "polygon" in the sketch layer.

**Comment by klassenjs** [comment]
Just writing down what I find while testing for OSGeo Live... figure it is better than ignoring it.

**Comment by theduckylittle** [comment]
Fixed in 2.8. This ended up being a fixed in other fixes.
