### ISSUE TITLE
USGS Layers in Demo returning blank images.

### ISSUE THREAD

**Issue by klassenjs** [geomoose/geomoose#70]
Not sure if it is a temporary service issue or the mapfile need updating.

**Comment by elil** [comment]
I think this is may be permanent.  MSRMaps has been trying to shut down for years.  It "permanently" shutdown in May 2012 but then started working again.

**Comment by elil** [comment]
Works today, http://demo.geomoose.org/cgi-bin/mapserv?MAP=%2Fsrv%2Fdemo%2Fsrc%2Fmaster%2Fmaps%2F%2Fdemo%2Fwms%2Fusgs.map&FORMAT=image%2Fpng&TRANSPARENT=TRUE&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&LAYERS=DRG&SRS=EPSG%3A3857&BBOX=-10377459.796641,5551190.9939971,-10374366.485653,5553386.1699029&WIDTH=1295&HEIGHT=919

**Comment by theduckylittle** [comment]
Can I close this or should we remove these layers from the demo ?

**Comment by elil** [comment]
Closing and keeping the layers makes sense to me.  We might want to replace these layers from the National Map (http://viewer.nationalmap.gov/example/services/serviceList.html) in the future.

**Comment by theduckylittle** [comment]
Noted.
