### ISSUE TITLE
Disable Tools when Using Services

### ISSUE THREAD

**Issue by theduckylittle** [geomoose/geomoose#72]
Users have been reporting real confusion that some tools are still available while they are using another.  Disabling the tools in the toolbar will prevent this from happening quite so readily.

**Comment by elil** [comment]
This does add more clicking to close and switch tools.  

Implementation looks nice in the demo. There is something unexpected, the "layer tools" drop down remains active even though all of its elements are inactive.  

This tangentially relates to #74 too.

**Comment by theduckylittle** [comment]
I'm closing the review period.  This does require more clicking but it also prevents the user from hurting themselves and GeoMOOSE getting generally confused.
