### ISSUE TITLE
Make Layer Editing Tools Contextual

### ISSUE THREAD

**Issue by theduckylittle** [geomoose/geomoose#74]
Right now all of the layer editing tools are up in the toolbar.  This makes them rather awkwards as there is a process of "activating" and "deactivating" layers from the catalog and then needing to access the editing tools in the toolbar.

I propose the following:
1. Remove the Layer Tools from the toolbar.
2. Allow users to select which layer controls they wish to have displayed ONLY on editable layers.
3. If CONFIGURATION.services.disable_others is set then selecting a layer tool will disable the toolbar until work on the layer has finished.
4. Change layer "activation" to a process of "unlocking" and "locking" for editing purposes.  Ensure there is a warning for unsaved changes when the layer is "locked" that changes would not necessarily have been saved.

Negative consequences:
1. It removes some of the "free roaming" nature of GeoMOOSE.
2. It will make some of the editing tools a bit less obvious as they will be changed to small (though CSS stylable) icons under the layer instead of larger, more readable menu items).

Positive consequences:
1. I think it makes the workflow more clear to users.
2. It allows administrators to configure which and how they want layers to work.
3. The workflow is more inline with Desktop GIS systems.  There is widespread debate as to whether or not this is a benefit.  Given GeoMOOSE's target audience as of late (replacement for desktop GIS) then I think it is still a reasonable target goal.
4. It allows us to remove the goofy drop-down menu which just burys functionality anyway.

**Comment by elil** [comment]
The layer tools have previously served two different purposes:
* Freestyle on screen drawing and annotation resulting in in-browser vectors that show up in printing and are as temporary as the browser session.
* WFS-T editing tools used on screen to send data to some serverside datastore through WFS-T.  

Is this proposal to remove the first function of freestyle in-browser vectors and make the WFS-T editing tools more specific to individual WFS-T capable layers?  Separating these two functions would be great.  Making the WFS-T tools more layer specific would be an improvement too.  I think that there is still a substantial role for the freestyle on screen markup.  

For the "activation" "unlocking" and 'locking" we might want to stay close to the language and icons of established analogies/workflows.  Here is a QGIS screenshot.
![qgis_pencil_editing](https://cloud.githubusercontent.com/assets/5263258/6785869/b610c0c6-d145-11e4-95b6-8254c461566a.png) "Pencils" and 3.5 floppies seem to be the editing icon language.  

Buried drop down functionality is fine for rarely accessed and related tools.

**Comment by theduckylittle** [comment]
The "just draw anywhere on the Map" aspect of the GeoMOOSE drawing tools has been a bit of a lie. 

Really, what has happened is that the "drawing and markup" layer has been activated by default in the last few releases.  This can be problematic if someone is using the popups or using the vector editing capabilities because you can get (as @klassenjs likes to call it), "Tool Confusion."  It's hard to determine where and when a particular tool is valid or active -- including "draw polygon" or "draw point."

There are also issues now that if a vector layer should *only* be points, lines, or polygons that a less useful error is generated.  Instead, under this modal, only the "draw polygon" or "draw point" tool will be available when that layer is "editable."

I'm all for harvesting similar noun representations from QGIS and others.

**Comment by bblammo** [comment]
All,

What about setting them up in a right click menu.  You can still leave 
the on/off toggle layer dependent this way, and there seems like there 
might be some other things that could be added to a right click menu 
over time.

bobb

**Comment by theduckylittle** [comment]
No right click menus. Ever. They are the devils spawn of evil. Lots of reasons, here are some poignant ones:
1. Not everyone uses a mouse, much less one with two buttons.
2. The browser already wants to do useful things with that menu. 
3. Right click menus hide important functionality from the user. If it is throw away or developer stuff, that's one thing, if its core usability, that should be exposed in an obvious fashion.

**Comment by elil** [comment]
I didn't catch some of the nuances of this initially.  Here is an attempt to summarize and clarify this.  

The way that the layer tools currently is that there are 0 or more WFS-T layers in the catalog and there is also a default, hidden, and activated layer that these tools automatically work on.  If you have 0 WFS-T layers then everything is simple and that is the end of the story.  If you have more than 0 WFS-T layers, then you have to activate (only one layer at a time) each layer you want these tools to work on. 

This proposes to move the default, hidden, and activated layer to a visible layer in the catalog.  This will make it obvious that there is a layer that the non-WFS-T function of these tools work on.  It will also allow the toggling of visibility of this layer.  Also, the tools will move away from the top toolbar and be integrated into the layer (I think).  There will also be an optional configuration to disable the toolbar while using these tools (i.e. eliminate possibility of "tool confusion").

Both of the following functionalities would continue:
* Freestyle on screen drawing and annotation resulting in in-browser vectors that show up in printing and are as temporary as the browser session (this would also have a corresponding layer in the catalog).
* WFS-T editing tools used on screen to send data to some serverside datastore through WFS-T.

**Comment by theduckylittle** [comment]
As a part of this ticket I discovered a few things:
1. We need more icons.
2. We are using CSS sprites and I need to update the sprite system slightly.
3. We were not properly attributing the Silk icons to famfamfam.
4. I found GeoSilk but had to patch together a different download location from the original announcement 5-years ago. 

Revision master@7d4ba199a99ed209971f44e8d8e55aa3e46d0cbc attempts to right the licensing and attribution wrongs.  I'm going to take a whack at updating the sprite generation now.

**Comment by tchaddad** [comment]
I never fully understood why there was some duplication of icons in the all.png included with the demo. For one of our projects, I went in and swapped out some of the duplicates for other famfam items that were more usefult for the editing options.

http://www.coastalatlas.net/estuarymaps/images/all.png

![draw_menu](https://cloud.githubusercontent.com/assets/1042618/7094849/0befd2ec-df7a-11e4-94eb-31900911521b.png)

**Comment by theduckylittle** [comment]
:) Good news! It's better now. Less duplication.  I've got one more icon I want to clean up but then this is getting fairly ready for prime time.

**Comment by theduckylittle** [comment]
This has been in the demo for a while now.  I've tested it this morning.  A longer term task would be adding some usability tutorials.  And I have an enhancement ticket to file for this.
