### ISSUE TITLE
Google layers misbehaving on tablets

### ISSUE THREAD

**Issue by tchaddad** [geomoose/geomoose#75]
As reported on the list, and confirmed on iOS (Safari, Chrome) and Android (FF and Chrome) browsers, see: http://lists.osgeo.org/pipermail/geomoose-users/2015-March/005586.html 

Tiled base maps such as MapBox, MapQuest, ESRI, OSM, etc behave as expected in a tablet environment, but Google layers, when turned on, zoom to whole globe and are unresponsive.

**Comment by theduckylittle** [comment]
I've tested this on my Retina iPad, iPad 2, and Eli has tested on Android.  Callin' it good.

**Comment by Raymond65** [comment]
Test it at desktop(OL 2.13.1,Geomoose 2.8.1), Google Streets (using it as default) doe not work.

**Comment by theduckylittle** [comment]
Sorry for the delay, I'm re-opening this issue but I am testing Google Streets, on Firefox (latest) and Chrome (latest) with 2.8.1 and not seeing any bugs.  Can anyone else verify?

**Comment by Raymond65** [comment]
For GeoMoose Demo,
Backgrounds default is "None", click "Google Streets", it works.

Change "None" status to "off", "Google Streets" status to "on" as following:
<map-source name="google_streets" type="google" google-type="streets">
<layer name="all" status="on"/>
</map-source>

"Google Streets" does not display. Click "Google Satellite" and then click "Google Streets", it works.

**Comment by Raymond65** [comment]
GeoMoose Demo:
Backgrounds default is "None", click "Google Streets", it works.

Change "None" status to "off" and "Google Streets" status to "on" as following:
<layer name="all" status="on"/>
"Google Streets" does not display. Click "Google Satellite" and then click "Google Streets", it works.

**Comment by Raymond65** [comment]
GeoMoose Demo:
 Backgrounds default is "None", click "Google Streets", it works.

Change "None" status to "off" and "Google Streets" status to "on" as following:
map-source for "Google Streets": layer name="all" status="on"
 
"Google Streets" does not display. Click "Google Satellite" and then click "Google Streets", it works.

Change "Google Satellite" as default (status to "on"), it works. 

Testing on Firefox latest.

**Comment by theduckylittle** [comment]
I've been working on this for roughly an hour.  Google maps appears to make a request to an image and when it does not return (there's some sort of browser error) it then fails to load the tiles. 

This is really something we're going to struggle to fix as we're very dependent on OpenLayers for this type of functionality.  Currently, we're running the latest version of OL2 and may not really be able to fix this until we switch to OL3.

**Comment by tchaddad** [comment]
I think it's a fair compromise to say GeoMoose does not support Google maps layers on tablets at this time. If all other background formats are working, it's not the end of the world.
