### ISSUE TITLE
Measure Tool Confusion

### ISSUE THREAD

**Issue by klassenjs** [geomoose/geomoose#79]
Version: the demo (g5f2c3b6).

Steps to reproduce:
1. Reload GeoMoose
2. Click "Measure Length" tool.
3. Click "Measure Area" tool.
(Note: the order of clicking on the length/area tools doesn't matter.  This is probably not specific to the measure tools but it is where we found the discrepancy.)

Results:
Pan tool is hilighted in the toolbar and the cursor is the hand (pan).  (Note: The Measure Area tab opens and clicking in the map measures area as expected.)

Expected Results:
Measure Area tool is highlighted in the toolbar and the cursor is the measure area cursor.

To get back to expected behavior:
Select one of the zoom tools twice (first time the pan tool stays selected in the toolbar, but zoom is active on the map) then select a measure tool.

**Comment by theduckylittle** [comment]
I found how these were interacting.  It actually got at a core operation bug with delinating between when a service/tool should be "selected" or "started" vs. when it was "clicked."
