### ISSUE TITLE
Remove (or comment) Virtual Earth <script>?

### ISSUE THREAD

**Issue by klassenjs** [geomoose/geomoose#80]
Propose removing the `<script src="http://dev.virtualearth.net..."> ` tag from geomoose.html and geomoose_dev.html.  It is not used in the demo, and I didn't find where it is used in the code.  (There is no GeoMOOSE/MapSource/VirtualEarth.js for instance.)  Does anyone object?

**Comment by theduckylittle** [comment]
I'm dropping 'em
