### ISSUE TITLE
Improve service tab control buttons

### ISSUE THREAD

**Issue by worknimble** [geomoose/geomoose#81]
1. Rename 'Cancel' to 'Close'
2. Make buttons more prominent

**Comment by theduckylittle** [comment]
I did a few things:
1. Converted the control button to Dijit Button's instead of native ones.
2. Made the buttons bigger.
3. Added Icons
4. Allowed the cancel/close button label to be changed with a configuration setting.

**Comment by theduckylittle** [comment]
Tested and doc'd.
