### ISSUE TITLE
Select by point selects too much

### ISSUE THREAD

**Issue by elil** [geomoose/geomoose#84]
While looking at #83, I ran into another problem.  

Try selecting 130220003076 with a point.  I get 2 results highlighted and two results in the csv.  The side bar only has one result.  There should only be 1 results highlighted and 1 results in the csv (and 1 results in the side bar).  

The built in [0.0001 buffer](https://github.com/geomoose/geomoose-services/blob/3204a2009bdabfa0208e550ca1e65c4e05c8eac6/php/select.php#L78) does not seem to be the cause of this.  

Polygon select seems to have some similar issue ![polygon_select_130220003076](https://cloud.githubusercontent.com/assets/5263258/7520004/85757210-f498-11e4-8982-e591cc115d24.png)

**Comment by theduckylittle** [comment]
More tests, more fun, more fix.

**Comment by elil** [comment]
Appears to work.
