### ISSUE TITLE
two point polygon selections cause error

### ISSUE THREAD

**Issue by elil** [geomoose/geomoose#85]
When selecting by polygon, two point polygons are allowed, this then throws an error in the service.  

&select_layer=parcels%2Fparcels&selection_buffer=0&query_layer=&shape_buffer=0&projection=EPSG%3A3857&shape=POLYGON((-10375742.69258%205555129.6328634%2C-10375734.33228%205555115.3009206%2C-10375742.69258%205555129.6328634))

Error Calling the server:
Error: Unable to load php/select.php status:500

**Comment by theduckylittle** [comment]
MapScript was, helpfully, throwing an exception which is now caught.  It assumes that the MapScript exception is a "bad geom" exception as MapScript doesn't do a great job of specifying various exceptions.

The user is now given an error that their geometry is not great and should try again.

**Comment by elil** [comment]
Demo is at https://github.com/geomoose/geomoose/commit/d000e21df8e93924124ed17dce4b6b5466f4141e submodules probably need to be updated to master to test in demo.

**Comment by theduckylittle** [comment]
Probably, I always get that mixed up.

Jim and I are already talking about paring down on submodules and switching
to something more package management friendly.

**Comment by theduckylittle** [comment]
We do have a test written which is some what comforting.  There are a
couple of conflicting tests that I need to finsih before we can look at
pushing 2.8 out the door.

**Comment by elil** [comment]
Tests are great for reminding you of those details :thumbsup:.

**Comment by elil** [comment]
Looks great!
