### ISSUE TITLE
Services interfere with drawing layer buffer, edit shapes, attribute, and remove feature

### ISSUE THREAD

**Issue by worknimble** [geomoose/geomoose#88]
The buffer tool stops working if any service is used. 
User can click on the buffer tool, the popup to Select feature opens, user clicks ok, unable to select any shapes. 
I've also noticed that if services are used and then user tries to use edit shape, edit attributes, or remove feature - user cannot select a shape.

**Comment by theduckylittle** [comment]
I'm not seeing this bug in the demo, will need to diagnose on the Saint Paul internal site.
