### ISSUE TITLE
Add an auto-refresh feature to GeoMOOSE

### ISSUE THREAD

**Issue by theduckylittle** [geomoose/geomoose#89]
Well... let's spec this out after I wrote the code:

````
<map-source ... auto-refresh="5000">
 ...
</map-source>
````

The auto-refresh attribute is specified in milliseconds.

**Comment by klassenjs** [comment]
Looks like it works to me.  My only comment is that it causes the layer to flash when it reloads.  This is worse when the Loading.js extension is used as the whole map dims under the loading spinny circle thing.  Is there something we could do with the OL transitions to avoid this?

**Comment by theduckylittle** [comment]
@klassenjs  -- Maybe.  I'm willing to call this a wrap for 2.8 and if someone wants something smoother but it together for a 2.8.1 or 2.9 release.  Do you want to file an enhancement ticket?

Also, I think if the refresh rate is reasonable (I've been testing 5 seconds, reasonable = 15s?), it'll be less noticeable.  Right now, however, we're using a mechanism that is very reliable and integrated reasonably well into OL.

**Comment by klassenjs** [comment]
Ok.

**Comment by kc0bqb** [comment]
I am using Geomoose 2.7.1 and I do not have a Layer.js file.  Is there a newer release?

Josh

**Comment by theduckylittle** [comment]
Not yet. We are working on 2.8 and getting really close. All the tickets
should be in review status by today and many are being tested for release
already.

**Comment by theduckylittle** [comment]
This is even documented! And tested! Yay!

**Comment by kc0bqb** [comment]
If I replace the MapSource.js and add the Layer.js to the GeoMoose folder will it work?  If not what else do I have to change to implement this feature?

 

 

 

Joshua Meyer

Lafayette County Sheriff's Office GIS

107 S 11th St

Lexington, MO 64067

Phone: 660-259-2796

Cell: 660-259-1234

Fax: 660-259-2545

**Comment by klassenjs** [comment]
There were lots of internal changes when Layer.js was introduced.  You can
either track them down and cherry-pick them with git, download the nightly
build and help us test, or wait a bit for the 2.8 release.
