### ISSUE TITLE
Multiple Mapbook.xml not working

### ISSUE THREAD

**Issue by hashifkaderi** [geomoose/geomoose#91]
I am using geomoose 2.7.1-ms4w. I cannot use multiple mapbooks using multiple settings.ini files as mentioned in the geomoose wiki.Even I tried alternative options such as avoid the getmapbook.php file then send the mapbook.xml file as url as mentioned by some users. it is fine but php services are not loading mapfile .

**Comment by theduckylittle** [comment]
Can you please move this to the geomoose-users mailing list? More people can help you there than can here in the ticket.

**Comment by elil** [comment]
The github issues are for reporting bugs or requesting enhancements or other things that usually result in changes to the code.  As Dan mentioned, the geomoose-users [mailing list] (http://geomoose.org/info/mailing_lists.html) is better.  

Clint provided some information on how he configured mulitple mapbooks in this [thread.] (https://lists.osgeo.org/pipermail/geomoose-users/2014-August/005392.html)
