### ISSUE TITLE
Configuration docs page is confusing

### ISSUE THREAD

**Issue by roemhildtg** [geomoose/geomoose#92]
I'm learning about Geomoose and one of the questions I had was configuring the tabs. [The configuration page](http://docs.geomoose.org/2.7/docs/configuration.html#configuration) mentions the tab configuration but the description is striped out. 

Any suggestions on using the additional tabs would be helpful. Edit: I now see the tabs parameter is depreciated, are tabs added through a different mechanism now?

**Comment by klassenjs** [comment]
It is striped out (and under the Deprecated Parameters heading) because the
information no longer applies to current versions of GeoMoose.

**Comment by theduckylittle** [comment]
Yes, if you look in the current demo there is a "Custom Tab" extension.  You can write your own extensions.  If you have any follow up questions please head on over to the geomoose-users mailing list  (http://www.geomoose.org/info/mailing_lists.html) which can put you in touch with other users who have been tackling similar problems.  

@klassenjs  and I also watch that list and help people from there.

**Comment by roemhildtg** [comment]
Great, thanks for the direction!
