### ISSUE TITLE
Add Legend to printable map (PDF output)

### ISSUE THREAD

**Issue by tchaddad** [geomoose/geomoose#99]
Place a legend showing layers turned on in the PDF output.

As mentioned here: http://lists.osgeo.org/pipermail/geomoose-users/2015-April/005601.html
and here: http://lists.osgeo.org/pipermail/geomoose-users/2015-July/005716.html

More to follow..

**Comment by theduckylittle** [comment]
So, apparently, we did not have legend rendering support.  And now we do. Huzzah!

**Comment by tchaddad** [comment]
Tested successfully in 97b9ce2 by inserting:`<param name="renderLegends">true</param>` into the mapbook.xml parameters. 

We should consider adding this to the demo mapbook so that users are aware that the option exists.

**Comment by elil** [comment]
The default mapbook.xml so far has been a balancing act of including the most common elements for example and reference and confusion with unnecessary information.  We could also consider the approach of include all options.  

I'll add this to the [Mapbook Reference Guide] (http://docs.geomoose.org/master/docs/mapbook.html).  Suggestions on where?

**Comment by tchaddad** [comment]
Understand about the demo. I was thinking that this was a common enough need (it's highly requested) that adding it as `<param name="renderLegends">false</param>` so that it is turned off by default wouldn't bee too intrusive.

As for the reference guide, the logical location is the configuration section at the top (since the guide is laid out like the Mapbook). But since that section mostly consists of copy-paste from the demo...

I assume it will also end up here?: http://docs.geomoose.org/master/docs/configuration.html#configuration

**Comment by elil** [comment]
Hmm, thinking about it, maybe it is better just in the configuration and not making the reference guide more crowded.  

Assuming that our [script](https://github.com/geomoose/geomoose-docs/blob/master/doc_config_js.py) that makes that page catches it, then yes, every config will be there.

@klassenjs should we update the [release process](https://github.com/geomoose/geomoose-website/blob/master/source/developer/release.rst) with something about running doc_config_js.py?  When does that get run?

**Comment by theduckylittle** [comment]
I set this as the default and fixed the code in master which had a regression that looked like I was testing some code.
